// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Technic.DAL;

namespace Technic.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181201132622_SpecsTypes")]
    partial class SpecsTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-preview1-35029")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Technic.DAL.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountRole");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<string>("Salt");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Technic.DAL.Models.IntermediateModels.MachineSpecification", b =>
                {
                    b.Property<Guid>("MachineId");

                    b.Property<Guid>("SpecificationId");

                    b.Property<string>("Value");

                    b.HasKey("MachineId", "SpecificationId");

                    b.HasIndex("SpecificationId");

                    b.ToTable("MachineSpecification");
                });

            modelBuilder.Entity("Technic.DAL.Models.IntermediateModels.MachineTypeSpecification", b =>
                {
                    b.Property<Guid>("MachineTypeId");

                    b.Property<Guid>("SpecificationId");

                    b.HasKey("MachineTypeId", "SpecificationId");

                    b.HasIndex("SpecificationId");

                    b.ToTable("MachineTypeSpecification");
                });

            modelBuilder.Entity("Technic.DAL.Models.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("MachineTypeId");

                    b.HasKey("Id");

                    b.HasIndex("MachineTypeId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("Technic.DAL.Models.MachineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("MachineTypes");
                });

            modelBuilder.Entity("Technic.DAL.Models.Specification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Specifications");
                });

            modelBuilder.Entity("Technic.DAL.Models.IntermediateModels.MachineSpecification", b =>
                {
                    b.HasOne("Technic.DAL.Models.Machine", "Machine")
                        .WithMany("Specifications")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Technic.DAL.Models.Specification", "Specification")
                        .WithMany("Machines")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Technic.DAL.Models.IntermediateModels.MachineTypeSpecification", b =>
                {
                    b.HasOne("Technic.DAL.Models.MachineType", "MachineType")
                        .WithMany("AllowedSpecifications")
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Technic.DAL.Models.Specification", "Specification")
                        .WithMany("MachineTypes")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Technic.DAL.Models.Machine", b =>
                {
                    b.HasOne("Technic.DAL.Models.MachineType", "MachineType")
                        .WithMany()
                        .HasForeignKey("MachineTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
