import common from './common';
import {
  FETCH_ONE_REQUEST,
  USER_AUTH_REQUEST,
  FETCH_ONE_SUCCESS,
  USER_AUTH_SUCCESS,
  FETCH_ONE_ERROR,
  USER_AUTH_ERROR,
  UPDATE_USER_ERROR,
  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS
} from '../../actions/user';

export default common({
  request: [FETCH_ONE_REQUEST, USER_AUTH_REQUEST, UPDATE_USER_REQUEST],
  success: [FETCH_ONE_SUCCESS, USER_AUTH_SUCCESS, UPDATE_USER_SUCCESS],
  error: [FETCH_ONE_ERROR, USER_AUTH_ERROR, UPDATE_USER_ERROR]
});
